"""Manage the board tokens that stand in for authentication.

A firm's board lives at ``/board/{token}`` and the token is the only thing
protecting it, so these are minted with ``secrets`` and never regenerated by
accident: an existing token is left alone unless rotation is asked for explicitly,
because rotating it breaks a link already in a customer's inbox.

The published site is keyed by ``sha256(token)`` — see ``profiles.schema`` — so a
token exists in exactly two places: this database, and the link you send.
"""

from __future__ import annotations

import argparse
import logging
import sqlite3

from profiles import schema


LOGGER = logging.getLogger(__name__)

BOARD_PATH = "/board"


def backfill(connection: sqlite3.Connection, now: str | None = None) -> list[dict]:
    """Give every firm without a token one. Idempotent."""
    rows = connection.execute(
        "SELECT id, name FROM firms WHERE board_token IS NULL OR board_token = '' "
        "ORDER BY id"
    ).fetchall()
    minted: list[dict] = []
    with connection:
        for row in rows:
            token = schema.generate_board_token()
            connection.execute(
                "UPDATE firms SET board_token = ?, updated_at = ? WHERE id = ?",
                (token, now or _timestamp(), int(row["id"])),
            )
            minted.append({"id": int(row["id"]), "name": str(row["name"]), "token": token})
            LOGGER.info("Minted a board token for firm %d (%s)", row["id"], row["name"])
    if not minted:
        LOGGER.info("Every firm already has a board token")
    return minted


def rotate(connection: sqlite3.Connection, firm_id: int, now: str | None = None) -> str:
    """Replace one firm's token, invalidating any link already sent."""
    row = connection.execute(
        "SELECT name FROM firms WHERE id = ?", (int(firm_id),)
    ).fetchone()
    if row is None:
        raise ValueError(f"No firm with id {firm_id}")
    token = schema.generate_board_token()
    with connection:
        connection.execute(
            "UPDATE firms SET board_token = ?, updated_at = ? WHERE id = ?",
            (token, now or _timestamp(), int(firm_id)),
        )
    LOGGER.warning(
        "Rotated the board token for firm %d (%s); any link already sent is now dead",
        firm_id,
        row["name"],
    )
    return token


def board_tokens(connection: sqlite3.Connection) -> list[dict]:
    """Every firm with a board, and the path to it."""
    rows = connection.execute(
        "SELECT id, name, board_token FROM firms "
        "WHERE board_token IS NOT NULL AND board_token != '' ORDER BY id"
    ).fetchall()
    return [
        {
            "id": int(row["id"]),
            "name": str(row["name"]),
            "token": str(row["board_token"]),
            "path": f"{BOARD_PATH}/{row['board_token']}",
            "hash": schema.board_token_hash(str(row["board_token"])),
        }
        for row in rows
    ]


def _timestamp() -> str:
    from notices import db

    return db.utc_timestamp()


def _main() -> None:
    parser = argparse.ArgumentParser(description="Manage firm board tokens")
    parser.add_argument("--db", default=None)
    parser.add_argument(
        "--backfill", action="store_true", help="mint tokens for firms without one"
    )
    parser.add_argument(
        "--rotate", type=int, default=None, metavar="FIRM_ID",
        help="replace a firm's token, invalidating the link already sent",
    )
    parser.add_argument(
        "--show", action="store_true", help="print each firm's board path"
    )
    args = parser.parse_args()

    connection = schema.connect(args.db)
    try:
        if args.backfill:
            minted = backfill(connection)
            print(f"minted {len(minted)} token(s)")
        if args.rotate is not None:
            token = rotate(connection, args.rotate)
            print(f"firm {args.rotate}: new path {BOARD_PATH}/{token}")
        if args.show or args.backfill:
            print("\nfirm boards:")
            for entry in board_tokens(connection):
                print(f"  {entry['id']:>3}  {entry['name'][:38]:<40} {entry['path']}")
            print(
                "\nSend each firm its own path once. The token is the access control; "
                "it is never published."
            )
    finally:
        connection.close()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    _main()
